use std::{
    cmp::Reverse,
    collections::BTreeMap,
    net::IpAddr,
    path::{Path, PathBuf},
    time::{SystemTime, UNIX_EPOCH},
};

use anyhow::{Context, Result, anyhow};
use serde::Serialize;

#[derive(Debug, Default)]
pub struct History {
    path: PathBuf,
    entries: BTreeMap<String, Vec<HistoryEntry>>,
}

#[derive(Debug, Clone, Serialize)]
pub struct HistoryEntry {
    pub changed_at: u64,
    pub ip: IpAddr,
}

impl History {
    pub async fn load(path: impl Into<PathBuf>) -> Result<Self> {
        let path = path.into();
        let raw = match tokio::fs::read_to_string(&path).await {
            Ok(raw) => raw,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                return Ok(Self {
                    path,
                    entries: BTreeMap::new(),
                });
            }
            Err(error) => {
                return Err(error)
                    .with_context(|| format!("failed to read history file {}", path.display()));
            }
        };

        let mut entries = BTreeMap::new();
        for (index, line) in raw.lines().enumerate() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            let (key, entry) = parse_line(line).with_context(|| {
                format!("invalid history line {} in {}", index + 1, path.display())
            })?;
            entries.entry(key).or_insert_with(Vec::new).push(entry);
        }

        for history_entries in entries.values_mut() {
            history_entries.sort_by_key(|entry| Reverse(entry.changed_at));
        }

        Ok(Self { path, entries })
    }

    pub fn get(&self, key: &str) -> Option<IpAddr> {
        self.entries
            .get(key)
            .and_then(|entries| entries.first())
            .map(|entry| entry.ip)
    }

    pub fn latest_entry(&self, key: &str) -> Option<&HistoryEntry> {
        self.entries.get(key).and_then(|entries| entries.first())
    }

    pub fn entries(&self, key: &str) -> &[HistoryEntry] {
        self.entries.get(key).map(Vec::as_slice).unwrap_or(&[])
    }

    pub fn set(&mut self, key: impl Into<String>, ip: IpAddr, limit: usize) {
        let key = key.into();
        let entries = self.entries.entry(key).or_default();
        if entries.first().is_some_and(|entry| entry.ip == ip) {
            return;
        }

        entries.insert(
            0,
            HistoryEntry {
                changed_at: unix_now(),
                ip,
            },
        );
        entries.truncate(limit.max(1));
    }

    pub async fn save(&self) -> Result<()> {
        if let Some(parent) = self
            .path
            .parent()
            .filter(|parent| !parent.as_os_str().is_empty())
        {
            tokio::fs::create_dir_all(parent)
                .await
                .with_context(|| format!("failed to create {}", parent.display()))?;
        }

        let mut lines = String::new();
        lines.push_str("# Generated by DriftDNS. Format: RECORD_TYPE|UNIX_SECONDS|IP\n");
        for (key, entries) in &self.entries {
            for entry in entries {
                lines.push_str(key);
                lines.push('|');
                lines.push_str(&entry.changed_at.to_string());
                lines.push('|');
                lines.push_str(&entry.ip.to_string());
                lines.push('\n');
            }
        }

        write_text_file(&self.path, lines).await
    }
}

fn parse_line(line: &str) -> Result<(String, HistoryEntry)> {
    let mut parts = line.split('|');
    let key = parts
        .next()
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .ok_or_else(|| anyhow!("missing record type"))?;
    let changed_at = parts
        .next()
        .map(str::trim)
        .ok_or_else(|| anyhow!("missing timestamp"))?
        .parse::<u64>()?;
    let ip = parts
        .next()
        .map(str::trim)
        .ok_or_else(|| anyhow!("missing IP"))?
        .parse::<IpAddr>()?;

    if parts.next().is_some() {
        return Err(anyhow!("too many fields"));
    }

    Ok((key.to_string(), HistoryEntry { changed_at, ip }))
}

fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or(0)
}

async fn write_text_file(path: &Path, contents: String) -> Result<()> {
    let file_name = path
        .file_name()
        .and_then(|value| value.to_str())
        .unwrap_or("ddns-history");
    let tmp_path = path.with_file_name(format!("{file_name}.{}.tmp", std::process::id()));

    tokio::fs::write(&tmp_path, contents)
        .await
        .with_context(|| {
            format!(
                "failed to write temporary history file {}",
                tmp_path.display()
            )
        })?;
    tokio::fs::rename(&tmp_path, path).await.with_context(|| {
        format!(
            "failed to replace history file {} with {}",
            path.display(),
            tmp_path.display()
        )
    })
}

#[cfg(test)]
mod tests {
    use super::parse_line;

    #[test]
    fn parses_timestamped_history_line() {
        let (key, entry) = parse_line("AAAA|1710000000|2001:db8::1").unwrap();

        assert_eq!(key, "AAAA");
        assert_eq!(entry.changed_at, 1_710_000_000);
        assert_eq!(entry.ip.to_string(), "2001:db8::1");
    }

    #[test]
    fn rejects_legacy_history_line() {
        let error = parse_line("A=203.0.113.10").unwrap_err();

        assert!(error.to_string().contains("missing timestamp"));
    }
}
